data_source bigquery_connection:
  type: bigquery
  # account_info_json_path: ./keys.json
  use_context_auth: true
  # impersonation_account: database-sa@cloud-data-infrastructure.iam.gserviceaccount.com
  auth_scopes:
  - https://www.googleapis.com/auth/bigquery
  - https://www.googleapis.com/auth/cloud-platform
  - https://www.googleapis.com/auth/drive
  project_id: "cloud-data-infrastructure"
  dataset: premier_league_dataset
