name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info

  push:
    paths-ignore:
      - '.github/**'
      - 'api/**'
      - 'etl/**'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.pylintrc'
      - 'README.md'
    branches:
      - "main"
        
env:
  GAR_LOCATION: us-central1
  VERSION_NUMBER: '2.5'
  CLOUD_BUCKET: ${{ secrets.CLOUD_BUCKET }}
  EMAIL: ${{ secrets.EMAIL }}
  NAME: ${{ secrets.NAME }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGISTRY_REPO: ${{ secrets.REGISTRY_REPO }}
  WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
  WIF_SERVICE_ACCOUNT_ARTIFACT_REGISTRY: ${{ secrets.WIF_SERVICE_ACCOUNT_ARTIFACT_REGISTRY }}
  WIF_SERVICE_ACCOUNT_CLOUD_STORAGE: ${{ secrets.WIF_SERVICE_ACCOUNT_CLOUD_STORAGE }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
jobs:

  version-test:
    name: Run Streamlit with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Streamlit
        run: pip install streamlit

      - name: Run Streamlit app
        run: streamlit run streamlit_app.py

  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      exit_code: ${{ steps.check.outputs.exit_code }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Black
        run: python -m pip install black

      - name: Check Black Formatting
        id: check
        run: |
          black test.py --check || exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
        
  black-formatting:
    runs-on: ubuntu-latest
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.exit_code == 1 }}

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Install Black
          run: python -m pip install black

        - name: Apply Black Formatting
          run: black test.py

        - name: Commit Changes
          run: |
            git config --local user.email "${{ env.EMAIL }}"
            git config --local user.name "${{ env.NAME }}"
            git add .
            git commit -m "Apply Black Formatting" --allow-empty
            git push

  build-streamlit-image:
    runs-on: ubuntu-latest
    needs: [check-for-changes, black-formatting]
    if: |
      always() &&
      (needs.black-formatting.result == 'success' || needs.black-formatting.result == 'skipped')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Prepare Docker Build Context
        run: |
          mkdir docker-context
          mkdir docker-context/.streamlit
          cp ./.dockerignore docker-context
          cp ./Dockerfile docker-context
          cp ./streamlit_app.py docker-context
          cp ./requirements.txt docker-context
          cp -r ./.streamlit/config.toml docker-context/.streamlit
        
      - name: Build and Export
        uses: docker/build-push-action@v4
        with:
          context: ./docker-context
          tags: streamlit:${{ env.VERSION_NUMBER }}
          outputs: type=docker,dest=/tmp/streamlit.tar
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: streamlit
          path: /tmp/streamlit.tar
          
  push-streamlit-image:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    needs: [build-streamlit-image]
    if: |
      always() &&
      (needs.build-streamlit-image.result == 'success')
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: streamlit
          path: /tmp
          
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT_ARTIFACT_REGISTRY }}'
          project_id: '${{ env.PROJECT_ID }}'
          
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v2'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        
      - name: Load Image
        run: |
          docker load --input /tmp/streamlit.tar
          docker image ls -a
          
      - name: Tag Image
        run: |
          docker tag \
          streamlit:${{ env.VERSION_NUMBER }} \
          "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_REPO }}/streamlit:${{ env.VERSION_NUMBER }}"
          
      - name: Push Image
        run: |
          docker push \
          "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_REPO }}/streamlit:${{ env.VERSION_NUMBER }}"
          
  deploy-streamlit-image:
      permissions:
        contents: 'read'
        id-token: 'write'
      
      runs-on: ubuntu-latest
      needs: [push-streamlit-image]
      if: |
        always() &&
        (needs.build-streamlit-image.result == 'success')
        
      steps:
      
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Google Auth
          id: auth
          uses: 'google-github-actions/auth@v1'
          with:
            token_format: 'access_token'
            workload_identity_provider: '${{ env.WIF_PROVIDER }}'
            service_account: '${{ env.WIF_SERVICE_ACCOUNT_ARTIFACT_REGISTRY }}'
            project_id: '${{ env.PROJECT_ID }}'
            
        - name: Deploy Image
          id: 'deploy'
          uses: 'google-github-actions/deploy-cloudrun@v1'
          with: 
            service: streamlit
            image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_REPO }}/streamlit:${{ env.VERSION_NUMBER }}"
            secrets: /app/.streamlit/secrets.toml=secrets_toml:latest
            flags: "--add-cloudsql-instances=cloud-data-infrastructure:us-central1:premier-league-postgres"
          
  syft:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    needs: [build-streamlit-image]
    if: |
      always() &&
      (needs.build-streamlit-image.result == 'success')
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: streamlit
          path: /tmp
        
      - name: Load Image
        run: |
          docker load --input /tmp/streamlit.tar
          docker image ls -a
          
      - uses: anchore/sbom-action@v0
        with:
          image: streamlit:${{ env.VERSION_NUMBER }}
          artifact-name: streamlit-sbom-${{ env.VERSION_NUMBER }}.spdx.json
          upload-artifact: true
          
  grype:
    permissions:
      actions: read
      contents: read
      security-events: write
      
    needs: [syft]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/download-artifact@v3
        with:
          name: streamlit-sbom-${{ env.VERSION_NUMBER }}.spdx.json
          
      - name: Scan SBOM
        uses: anchore/scan-action@v3
        id: scan
        with:
          sbom: streamlit-sbom-${{ env.VERSION_NUMBER }}.spdx.json
          fail-build: false
          output-format: sarif
          severity-cutoff: critical
          
      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
  
  security:
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
        - uses: actions/checkout@v3
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/python-3.10@master
          continue-on-error: true # To make sure that SARIF upload gets called
          env:
            SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
          with:
            args: --sarif-file-output=snyk.sarif
        - name: Upload result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: snyk.sarif
