name: CI/CD - Streamlit App

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info

  push:
    paths-ignore:
      - '.github/**'
    branches:
      - 'main'
      - '!test'
      
  pull_request:
    branches:
      - 'main'
      - 'fix'
      - '!test'
        

jobs:
  streamlit-tests:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # build SQLite from source, because I need 3.35<=
    - run: |
        wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
        tar -xvf sqlite-autoconf-3380500.tar.gz
    - run: |
        ./configure
        make
        sudo make install
        export PATH="/usr/local/lib:$PATH"
      working-directory: sqlite-autoconf-3380500

    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install streamlit

    - name: Pytest Run
      run: |
         pytest --cov=streamlit_app tests/ -v
      env:
        LD_LIBRARY_PATH: /usr/local/lib
  
  test-2:
    runs-on: ubuntu-22.04
    needs: streamlit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # You can specify your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

