name: CI/CD - Streamlit App

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info

  push:
    paths-ignore:
      - '.github/**'
      - 'soda/**'
      - 'README.md'
    branches:
      - 'main'
      - '!test'
      
  pull_request:
    branches:
      - 'main'
      - 'fix'
      - '!test'

jobs:
  streamlit-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.txt

    - name: Pytest Run
      run: |
         pytest --cov=streamlit_app tests/ -v
  
  test-2:
    runs-on: ubuntu-22.04
    needs: streamlit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # You can specify your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

