name: CI/CD - Streamlit App

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info

  push:
    paths-ignore:
      - '.github/**'
    branches:
      - 'main'
      - '!test'
      
  pull_request:
    branches:
      - 'main'
      - 'fix'
      - '!test'
        

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # You can specify your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

