name: CI/CD - Streamlit App

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info

  push:
    paths-ignore:
      - '.github/**'
      - 'soda/**'
      - 'README.md'
    branches:
      - 'main'
      - '!test'
      
  pull_request:
    branches:
      - 'main'
      - 'fix'
      - '!test'

jobs:
  streamlit-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Python Setup
      uses: actions/setup-python@4
      with:
        python-version: '3.11.6'

    - name: Install Pytest and Plugins
      run: |
        pip install pytest==7.4.3                               
        pytest-cov==4.1.0

    - name: Run Pytest Checks
      run: |
        pytest --cov=streamlit_app tests/ -v

